#!/bin/sh -e

##########################################################################
#   Script description:
#       Install miniconda on a FreeBSD system
#       
#   History:
#   Date        Name        Modification
#   2018        Jason Bacon Begin
##########################################################################

usage()
{
    printf "Usage: $0\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 0 ]; then
    usage
fi

if [ -e /usr/local/sbin/node-type ] && [ $(/usr/local/sbin/node-type) != compute ]; then
    printf "Error: $0 should only be run on compute nodes.\n"
    exit 1
fi

for dir in proc dev sys; do
    if [ ! -e /compat/linux/$dir ]; then
	cat << EOM

Missing /compat/linux/$dir.  Run "pkg install auto-admin" and
"auto-install-linux_base" as root to complete the Linux compatibility setup.

EOM
	exit 1
    fi
done
if [ ! -e /usr/local/bin/python3.8 ]; then
    cat << EOM

This miniconda requires python3.8.  Install lang/python38 and try again.

EOM
    exit 1
fi

if [ ! -e ~/miniconda3 ]; then
    script=Miniconda3-latest-Linux-x86_64.sh
    if [ ! -e $script ]; then
	fetch https://repo.anaconda.com/miniconda/$script
    fi
    /compat/linux/bin/sh Miniconda3-latest-Linux-x86_64.sh
else
    printf "miniconda3 already present.  Not reinstalling.\n"
fi

cat << EOM

To use the conda environment, run "conda-shell".

EOM
while [ 0"$resp" != 0"got it" ]; do
    read -p 'Type "got it" to confirm. ' resp
done
